add cloud function for twitter bot
kaogeek/fact-finder pull request #16
Opened 2021-08-17 18:38 UTC by chaintng

- add firestore and pubsub in emulator
- enable `--inspect-functions` for vscode debugging (More info: https://medium.com/firebase-developers/debugging-firebase-functions-in-vs-code-a1caf22db0b2)
- add `scoutTwitter` function for scheduling job scraping tweets. (Blocked by Twitter API access)
- add `scoutTwitterLastUpdate` function to check last update in firestore

2021-08-17 21:54 UTC, vtno requested changes
มีติด region หายไปนิดนึงครับกับเหมือนจะยังเป็น WIP อยู่ ผมส่ง Twitter token ให้แล้วน่าจะทำต่อได้

2021-08-17 21:54 UTC, vtno commented on backend/twitter-bot/index.js
> +exports.scoutTwitter = functions.pubsub.schedule("0 7 * * *").onRun((context) => {
เหมือน region จะหายไปนะครับ

2021-08-17 21:54 UTC, vtno commented on backend/twitter-bot/index.js
> +exports.scountTwitterLastUpdate = functions
อันนี้ทำไมถึงมีอีก function หรอครับ?​ ผมไม่ค่อยเกท

2021-08-18 03:23 UTC, chaintng commented on backend/twitter-bot/index.js
> +exports.scountTwitterLastUpdate = functions
อันนี้ ทดลองเฉยๆ ไม่มีอะไรคับ เดี๋ยวลบทิ้งคับ

2021-08-18 03:23 UTC, chaintng commented on backend/twitter-bot/index.js
> +exports.scoutTwitter = functions.pubsub.schedule("0 7 * * *").onRun((context) => {
โอเคคับ

2021-08-19 03:12 UTC, merged